# Exported from Render on 2026-08-09T04:08:54Z
version: "1"
services:
- type: web
  name: prime-crest-tracking-api-jjtg
  runtime: python
  repo: https://github.com/savagedirane/prime-tracking
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: JWT_EXPIRES_MINUTES
    sync: false
  - key: JWT_SECRET
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  autoDeployTrigger: commit
  rootDir: backend
