"""
Small shared helpers — currently just server-side tracking-number generation.

Tracking numbers are generated by the server (never accepted verbatim from
clients by default) because client-chosen numbers are guessable and can be
enumerated to discover other people's shipments. The format is:

    PCL + 11 random digits + 1 Luhn check digit   (e.g. PCL842150937615)

That's ~100 billion combinations with a validity check built in — safe to
expose publicly, and any transposed digit is caught before a DB lookup.
"""
import random
import string

from sqlalchemy import select
from sqlalchemy.orm import Session

import models

TRACKING_PREFIX = "PCL"


def _luhn_check_digit(digits: str) -> int:
    """Compute the Luhn check digit for a string of decimal digits."""
    total = 0
    for i, ch in enumerate(reversed(digits)):
        d = int(ch)
        if i % 2 == 0:
            d *= 2
            if d > 9:
                d -= 9
        total += d
    return (10 - total % 10) % 10


def is_valid_tracking_number(tracking_number: str) -> bool:
    """True if the number is in the server-generated PCL format (Luhn-valid)."""
    if (
        len(tracking_number) != len(TRACKING_PREFIX) + 12
        or not tracking_number.startswith(TRACKING_PREFIX)
        or not tracking_number[len(TRACKING_PREFIX):].isdigit()
    ):
        return False
    body = tracking_number[len(TRACKING_PREFIX):-1]
    return _luhn_check_digit(body) == int(tracking_number[-1])


def generate_tracking_number(db: Session) -> str:
    """Return an unused tracking number, retrying on the (astronomically
    unlikely) collision. The unique index on tracking_number is the final
    authority — an IntegrityError at flush means we lost a race and the
    request should simply be retried."""
    for _ in range(10):
        body = "".join(random.choices(string.digits, k=11))
        candidate = f"{TRACKING_PREFIX}{body}{_luhn_check_digit(body)}"
        exists = db.scalar(
            select(models.Shipment.id).where(models.Shipment.tracking_number == candidate)
        )
        if not exists:
            return candidate
    raise RuntimeError("Could not generate a unique tracking number after 10 tries")
